# Generated by Django 4.1.1 on 2022-10-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followering',
            new_name='following',
        ),
    ]
