# Generated by Django 4.1.1 on 2022-10-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserName',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='username',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='repo_name',
            new_name='repository',
        ),
    ]
