# Generated by Django 4.1.1 on 2022-10-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_finder', '0002_rename_followering_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
